CREATE DATABASE CREDITFACILITY;

CREATE TABLE USER (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    EMAIL varchar(255),
    FIRST_NAME varchar(255),
    LAST_NAME varchar(255),
    PASSWORD varchar(255),
    ROLE varchar(255),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE TOKEN (
    TOKEN_ID INT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP WITHOUT TIME ZONE,
    TOKEN VARCHAR(255),
    USER_ID INT NOT NULL,
    PRIMARY KEY (TOKEN_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)

CREATE TABLE LOAN (
    LOAN_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    LOAN_AMOUNT FLOAT,
    LOAN_TYPE VARCHAR(255),
    PRIMARY KEY (LOAN_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);
